version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: weather_forecast_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Rails Application
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/weather_forecast_development
      - REDIS_URL=redis://redis:6379/0
      - OPENWEATHER_BASE_URL=https://api.openweathermap.org/data/2.5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: >
      sh -c "
        rm -f /app/tmp/pids/server.pid &&
        bundle install &&
        rails db:create &&
        rails db:migrate &&
        rails server -b 0.0.0.0
      "

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
